### ISSUE TITLE
FileIndexer fails to convert PDF, how to fix:

### ISSUE THREAD

**Issue by gripfastartworks** [lfschenone/FileIndexer#1]
remove commenting slashes from line 77 within file: FileIndexer.config.php

// 'pdf' => WC_FI_COMMAND . "[pdftotext] -raw -nopgbrk \"" . WC_FI_FILEPATH . "\" -| " . WC_FI_COMMAND . "[iconv] -f ISO-8859-1 -t UTF-8",

You will need to install all listed dependencies lines 58 - 66.

**Comment by lfschenone** [comment]
On behalf of all future users, thanks! I just commited this change.
